### ISSUE TITLE
False positive with version_constraints_missing_whitespace test

### ISSUE THREAD

**Issue by AndrewVallette** [anaconda-distribution/anaconda-linter#113]
When linting the `numba` feedstock with the `update_0.56.3` branch, the following false positives are generated:

**ERROR: /tmp/abs_5a4ybtzi5d/clone/recipe/meta.yaml:45: version_constraints_missing_whitespace: Packages and their version constraints must be space separated
ERROR: /tmp/abs_5a4ybtzi5d/clone/recipe/meta.yaml:48: version_constraints_missing_whitespace: Packages and their version constraints must be space separated**

These are lines 45 through 48:

```
    - numpy {{ numpy_min_ver }}
    - tbb-devel 2021.*,<2021.6
    - _openmp_mutex            # [linux]
    - importlib_metadata       # [py<39]

```

There are no whitespace issues with any constraints here, so the linter seems to be incorrect. Also, note that this issue was occurring before `numpy` was pinned at all (the line previously was ` - numpy`).

**Comment by marcoesters** [comment]
The linter expected a `=` there. I expanded the check to accept this version, too, since this is valid syntax.
