### ISSUE TITLE
Linter in Prefect Build is noisy

### ISSUE THREAD

**Issue by razzlestorm** [anaconda-distribution/anaconda-linter#122]
Linter will run multiple times and paste full error/warning messages on every run, which can end up being visually noisy. If there is a way to either delete previous comments or edit/add on to one comment, it might be visually cleaner.

**Comment by AndrewVallette** [comment]
Updating the original comment (if there is one) would be nice. If that doesn't work, then perhaps they could show up as collapsed by default. I dont know if any of that is possible, though.

**Comment by marcoesters** [comment]
Or is it possible to access the linter logs instead of having a comment in the PR?

**Comment by razzlestorm** [comment]
Currently [Pull+552](https://github.com/anaconda-distribution/rocket-platform/pull/552) from @cbouss makes the linter default to collapsed. Is that enough to close this issue?

**Comment by schuylermartin45** [comment]
Now that we also have this open issue, https://github.com/anaconda-distribution/anaconda-linter/issues/227, I'm going to make the executive decision and close this issue. I think the new issue tracks our current gripes with the error output.
