### ISSUE TITLE
Yaml parsing error

### ISSUE THREAD

**Issue by bkreider** [anaconda-distribution/anaconda-linter#126]
I have an example of valid recipe that the linter breaks on trying to read the yaml.  

Here is the comment link from the PR: https://github.com/AnacondaRecipes/dotnet-feedstock/pull/1#issuecomment-1304211253

**Comment by marcoesters** [comment]
The ruamel.yaml parser breaks on the ".NET" string. A workaround could be to wrap the summary in quotes.

However, we should investigate why the conda-build parser manages to parse that file.

**Comment by cbouss** [comment]
The issue is actually the selector on the summary line.
`summary: |                                                                      # [win]`
But I added code in PR #131 to handle yaml errors.
