### ISSUE TITLE
Issues with `spdx` compliant licenses

### ISSUE THREAD

**Issue by varlackc** [anaconda-distribution/anaconda-linter#127]
The linter has an issue for some reason it does not recognnize the following license as spdx compliant:

Artistic-1.0-Perl
https://spdx.org/licenses/Artistic-1.0-Perl.html

Here is a complete list of `spdx complient licenses`
https://spdx.org/licenses/

**Comment by razzlestorm** [comment]
I can't replicate this issue, but I remember that there was a feedstock it wasn't working on. Which was it?

**Comment by varlackc** [comment]
Here is the original PR that had the failure on the License section. 

`Moved Perl to 5.34.0` 
https://github.com/AnacondaRecipes/perl-feedstock/pull/7
