### ISSUE TITLE
Documentation of known issues for the `anaconda-linter`

### ISSUE THREAD

**Issue by varlackc** [anaconda-distribution/anaconda-linter#157]
### Discussed in https://github.com/anaconda-distribution/anaconda-linter/discussions/156

<div type='discussions-op-text'>

<sup>Originally posted by **varlackc** December 16, 2022</sup>

## Documentation of known issues for the `anaconda-linter`

    It might be a good idea to keep track of known issues and discuss them in order to plan the next issues to track in the next version of `Anaconda-Linter`

</div>

**Comment by marcoesters** [comment]
This is typically done in the Issues. Manually keeping track seems like unnecessary maintenance overhead.

**Comment by varlackc** [comment]
That might be a good point, I am just thinking in terms of planning to keep track of the important issues.
