### ISSUE TITLE
Directly specifying a compiler requirement is sometimes desired

### ISSUE THREAD

**Issue by danpetry** [anaconda-distribution/anaconda-linter#205]
See https://github.com/AnacondaRecipes/librsvg-feedstock/blob/a5f9d544032d0acedf3e40736618d0c36ee7e61b/recipe/meta.yaml#L43

I'm not sure why this was done here, but looks intentional. Could downgrade this lint from an error to a warning?

**Comment by marcoesters** [comment]
Unless there are any objections, I will close this since there is a mechanism to add exceptions
