### ISSUE TITLE
Audit test coverage - aim for and enforce >=80%

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/anaconda-linter#230]
I know there are other unit test tickets already filed, but this ticket is a call to action to audit the test coverage and test cases of the project.

We need to audit and then enforce a minimum test coverage threshold. PRs should not be accepted if the test coverage is below a certain threshold.

This will allow us to prevent regressions, which is a key step towards future automation projects.

**Comment by razzlestorm** [comment]
TODO: Validate that `make test` is producing a metric we're happy with.

**Comment by schuylermartin45** [comment]
Enforcement is now being done. Closing.
