### ISSUE TITLE
Add full usage message section to README

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/anaconda-linter#231]
IMO, it is very useful to have the full `usage` message from `-h` in the `README`.

This means that at a glance, I can view what the tool can do.

This is helpful for people who haven't used the tool before and want to look before they clone. It is also useful as a reference when writing feature enhancement issues.

**Comment by razzlestorm** [comment]
Add towards top, after installation, as subheading.

**Comment by schuylermartin45** [comment]
Done
