### ISSUE TITLE
`noarch: python` Rule

### ISSUE THREAD

**Issue by schuylermartin45** [anaconda-distribution/anaconda-linter#235]
Some credit goes to @ELundby45 for this idea

I've seen `noarch: python` -> `skip: true # [py<37]` as a suggested piece of feedback in several of my PRs lately.

Should we add it as a rule to catch that mistake?

**Comment by marcoesters** [comment]
You mean this one? https://github.com/anaconda-distribution/anaconda-linter/blob/main/anaconda_linter/lint/check_build_help.py#L429

If you have noarch packages that the Linter doesn't catch, then there is a bug in the linter.

**Comment by schuylermartin45** [comment]
I just re-ran a test as a sanity check and I guess I found a bug.

In fact, I don't think I've ever seen this rule trigger a warning, so it might be more than one package.

**Comment by marcoesters** [comment]
I can reproduce this. I will take a look
