### ISSUE TITLE
Exclude packaging from python_build_tool_in_run

### ISSUE THREAD

**Issue by philippjfr** [anaconda-distribution/anaconda-linter#263]
`panel` and various other libraries that I know use `packaging` for a variety of reasons at runtime so the `python_build_tool_in_run` check frequently incorrectly flags it. I'd be okay with continuing to skip this rule in the relevant recipes but on balance I'd prefer it to be excluded.

**Comment by marcoesters** [comment]
Can you provide an example where this is happening?

`packaging` has been removed from this list since the linter version `0.1.0`

**Comment by marcoesters** [comment]
You may have come across it as the new version was being deployed - it shouldn't be happening anymore.

**Comment by schuylermartin45** [comment]
It sounds like this issue has been resolved and there has been no action from the requester in providing more details.
Closing.

Please feel free re-open with additional details if this is still a problem or contact the Packaging Automation Team directly through internal means.
