### ISSUE TITLE
VS code integration

### ISSUE THREAD

**Issue by cbouss** [anaconda-distribution/anaconda-linter#61]
Would be call to have the linter run on meta.yaml changes with vscode.
Perhaps this could help: https://marketplace.visualstudio.com/items?itemName=hchiam.custom-vscode-linter

**Comment by schuylermartin45** [comment]
I'm going to go ahead and make this a "won't do" as we are such a small team, I can't imagine this is sustainable.

As a stop gap, there are several ways to integrate shell commands into VS Code (plugins and native support).
