### ISSUE TITLE
Make filepath strings in results relative to feedstock base directory

### ISSUE THREAD

**Issue by danpetry** [anaconda-distribution/anaconda-linter#98]
E.g.:

`ERROR: /Users/dpetry/Sandbox/aggregate/blinker-feedstock/recipe/meta.yaml: ...`

becomes

`ERROR: recipe/meta.yaml: ...`

This will clean up github linter messages too.

**Comment by marcoesters** [comment]
Another option, or an additional enhancement would be to not display the file name if there is only one recipe to lint.

**Comment by danpetry** [comment]
Is the file in question always going to be meta.yaml? Or does the linter look at other things too (e.g. folder structure, files present etc)

**Comment by marcoesters** [comment]
I can't come up with an example where the recipe file is not `meta.yaml`. It does look at build scripts - see here: https://github.com/anaconda-distribution/anaconda-linter/blob/main/anaconda_linter/lint/check_build_help.py#L165

**Comment by danpetry** [comment]
> It does look at build scripts

yeah then I guess the filename is generally useful

**Comment by varlackc** [comment]
The following `Pull Request` could be used to address the issue with the `long file paths` in the linter reports

https://github.com/anaconda-distribution/anaconda-linter/pull/151

**Comment by marcoesters** [comment]
Closed by #241
